{% set name = "dotnet-script" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dotnet-script/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 775984197970156cd6b7397d74ab6c9709c64e4318b4a2658ef280801163f0d6

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/dotnet-script/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Run C# scripts from the .NET CLI
  dev_url: https://github.com/dotnet-script/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
