context:
  version: 1.5.0

package:
  name: dotnet-script
  version: ${{ version }}

source:
  url: https://github.com/dotnet-script/dotnet-script/archive/${{ version }}.tar.gz
  sha256: 2b22cd28b80bb7adf80888cd3259a4cff1c1e5c68eb78dc36107d6542c9ee6a2

build:
  number: 1
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-script --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Run C# scripts from the .NET CLI
  homepage: https://github.com/dotnet-script/dotnet-script
  repository: https://github.com/dotnet-script/dotnet-script

extra:
  recipe-maintainers:
    - danielnachun
