context:
  version: "1.6.0"

package:
  name: dotnet-script
  version: ${{ version }}

source:
  url: https://github.com/dotnet-script/dotnet-script/archive/${{ version }}.tar.gz
  sha256: 775984197970156cd6b7397d74ab6c9709c64e4318b4a2658ef280801163f0d6

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-script --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Run C# scripts from the .NET CLI
  homepage: https://github.com/dotnet-script/dotnet-script
  repository: https://github.com/dotnet-script/dotnet-script

extra:
  recipe-maintainers:
    - danielnachun
